from __future__ import annotations

import uuid
from datetime import datetime
from typing import TYPE_CHECKING

from sqlalchemy import (
    Boolean,
    CheckConstraint,
    DateTime,
    ForeignKey,
    Integer,
    String,
    Uuid,
    func,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database import Base
from app.models.role import DEFAULT_ROLE, ROLE_VALUES

if TYPE_CHECKING:
    from app.models.conversation import LiveInterviewSession
    from app.models.documents import DocumentChunk, ResumeDocument
    from app.models.interview import InterviewSession
    from app.models.organization import Organization
    from app.models.password_reset_token import PasswordResetToken
    from app.models.refresh_token import RefreshToken


class User(Base):
    """
    ORM model for the `users` table.

    Stores credentials and identity for every registered account.

    RBAC / multi-tenancy: every user has exactly one `role` (see
    app.models.role.Role) and an optional `organization_id`. Registration
    always assigns Role.CANDIDATE server-side (app.services.auth_service);
    only a Super Admin can change a user's role afterward
    (app.core.permissions.can_assign_roles). Organization membership is
    required for RECRUITER/ADMIN and optional for CANDIDATE — a candidate's
    organization_id is NULL until an Admin/Super Admin invites them into
    one; it is never set at self-registration.
    """

    __tablename__ = "users"
    __table_args__ = (
        CheckConstraint(
            f"role IN ({', '.join(repr(v) for v in sorted(ROLE_VALUES))})",
            name="ck_users_role",
        ),
    )

    # ------------------------------------------------------------------
    # Primary key
    #
    # UUID rather than an auto-incrementing integer for two reasons:
    #   1. IDs are exposed in API URLs. Sequential integers reveal the
    #      total number of users and make enumeration trivial — a
    #      meaningful privacy leak for an interview platform.
    #   2. UUIDs can be generated in Python before the INSERT, so the
    #      application knows the ID without a database round-trip.
    #      This simplifies code that constructs related objects in memory.
    #
    # sqlalchemy.Uuid (SQLAlchemy 2.x): cross-database UUID type.
    # Maps to the native UUID column in PostgreSQL and to CHAR(32) in
    # SQLite, which lets the test suite run without Docker.
    # Always returns Python uuid.UUID objects (not raw strings).
    #
    # default=uuid.uuid4: Python-side callable invoked before each INSERT.
    # The id is available immediately after db.add(user), before db.commit().
    # ------------------------------------------------------------------
    id: Mapped[uuid.UUID] = mapped_column(
        Uuid,
        primary_key=True,
        default=uuid.uuid4,
        comment="Unique user identifier. Generated by the application layer.",
    )

    # ------------------------------------------------------------------
    # Email address
    #
    # unique=True: enforced at the database level with a UNIQUE constraint,
    # not just at the application level. This prevents duplicate accounts
    # even under concurrent registration requests that both pass the
    # application-level check before either commits.
    #
    # index=True: creates a B-tree index on this column. Login queries
    # filter by email on every request — without an index, PostgreSQL
    # performs a sequential scan of the entire users table.
    #
    # String(255): matches the VARCHAR(255) in the SQL schema. 255 is the
    # conventional maximum for email addresses per RFC 5321.
    # ------------------------------------------------------------------
    email: Mapped[str] = mapped_column(
        String(255),
        unique=True,
        nullable=False,
        index=True,
        comment="User email address. Used as the login identifier.",
    )

    # ------------------------------------------------------------------
    # Password (hashed)
    #
    # The plaintext password is NEVER stored. The application passes the
    # plaintext through bcrypt (via passlib) which produces a string in
    # the Modular Crypt Format, e.g.:
    #   $2b$12$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36zLrvKSHXaHPHVFxDtM0e.
    #
    # This string encodes the algorithm ($2b$ = bcrypt), the cost factor
    # (12 rounds of key stretching), the salt (22 characters), and the
    # hash (31 characters). Total length is always 60 characters for bcrypt
    # — String(255) gives ample headroom if a different algorithm is used later.
    #
    # Verification: passlib.context.verify(plain_password, hashed_password)
    # The original password cannot be recovered from the stored hash.
    # ------------------------------------------------------------------
    hashed_password: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
        comment="bcrypt hash of the user password. Plaintext is never stored.",
    )

    # ------------------------------------------------------------------
    # Display name
    #
    # Stored as entered by the user at registration. Not used for
    # authentication — only for display in the UI and reports.
    # ------------------------------------------------------------------
    full_name: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
        comment="User's full name as entered at registration.",
    )

    # ------------------------------------------------------------------
    # Timestamp
    #
    # DateTime(timezone=True): maps to TIMESTAMPTZ in PostgreSQL, which
    # stores the moment in UTC regardless of the server's local timezone.
    # Always use timezone-aware timestamps — naive datetimes (without tz)
    # cause subtle bugs when comparing or sorting across timezone boundaries.
    #
    # server_default=func.now(): the default is computed by PostgreSQL
    # (NOW() → current transaction timestamp) rather than Python. This
    # guarantees the value is set even if a row is inserted by a migration
    # script or a direct SQL statement that bypasses the ORM.
    #
    # The Mapped[datetime] annotation (not Mapped[datetime | None]) tells
    # SQLAlchemy 2.x that this column is NOT NULL without needing an
    # explicit nullable=False argument.
    # ------------------------------------------------------------------
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        comment="UTC timestamp of account creation. Set by the database.",
    )

    # ------------------------------------------------------------------
    # Phase 3 — Login protection (brute-force / lockout)
    #
    # failed_login_attempts counts consecutive wrong-password attempts
    # since the last successful login or lockout. It resets to 0 on
    # every successful login and every time a new lockout is applied.
    #
    # locked_until: when set and in the future, login is rejected with
    # HTTP 423 regardless of whether the supplied password is correct.
    # Null means the account is not currently locked.
    #
    # lockout_count tracks how many times this account has been locked,
    # ever. auth_service uses it to compute progressive backoff:
    # duration doubles with each successive lockout, capped by
    # Settings.ACCOUNT_LOCKOUT_MAX_DURATION_MINUTES.
    # ------------------------------------------------------------------
    failed_login_attempts: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=0,
        server_default="0",
        comment="Consecutive failed login attempts since last success or lockout.",
    )

    locked_until: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        comment="If set and in the future, login is rejected (account locked).",
    )

    lockout_count: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=0,
        server_default="0",
        comment="Total number of times this account has been locked. Drives "
        "progressive lockout-duration backoff.",
    )

    # ------------------------------------------------------------------
    # Phase 3 — JWT token versioning
    #
    # Embedded as the "ver" claim in every access token issued for this
    # user. get_current_user rejects a token whose "ver" claim does not
    # match the current column value. Incrementing this column (on
    # logout-all-devices or password change) instantly invalidates every
    # previously issued access token without needing a blacklist store —
    # the cheapest form of revocation for a value that changes rarely.
    # ------------------------------------------------------------------
    token_version: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=0,
        server_default="0",
        comment="Incremented to invalidate all previously issued access tokens.",
    )

    # ------------------------------------------------------------------
    # RBAC / multi-tenancy
    #
    # role: plain string, not a native DB ENUM — see Role's docstring for
    # why (matches InterviewSession.status's existing convention). Guarded
    # at the DB level by ck_users_role above, and validated again in
    # Python via app.models.role.ROLE_VALUES anywhere a role is assigned
    # outside the ORM's own CHECK-constraint enforcement (e.g. before a
    # commit, so the error surfaces as a clean 422/400 instead of an
    # IntegrityError from the database driver).
    #
    # organization_id: nullable — required in practice for RECRUITER/ADMIN
    # (enforced in app.services.auth_service / admin recruiter-creation,
    # not by a DB constraint, since a CANDIDATE legitimately has NULL
    # here). ON DELETE SET NULL: deactivating/deleting an organization
    # must never cascade-delete the people who were in it.
    #
    # is_active: sits on User (not just Organization) so an Admin can
    # deactivate a single recruiter without touching their organization.
    # Checked in get_current_user-adjacent authorization, not baked into
    # get_current_user itself — see app.core.deps.require_active_user.
    # ------------------------------------------------------------------
    role: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
        default=DEFAULT_ROLE,
        server_default=DEFAULT_ROLE,
        comment="One of Role's values. Assigned CANDIDATE at registration; "
        "changed only by a Super Admin thereafter.",
    )

    organization_id: Mapped[uuid.UUID | None] = mapped_column(
        Uuid,
        ForeignKey("organizations.id", ondelete="SET NULL"),
        nullable=True,
        comment="NULL for an unaffiliated candidate. Required in practice for "
        "RECRUITER/ADMIN accounts, which are always created already assigned "
        "to an organization.",
    )

    is_active: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=True,
        server_default="true",
        comment="Deactivated accounts (e.g. an offboarded recruiter) fail "
        "authorization even with a valid, unexpired JWT.",
    )

    organization: Mapped["Organization | None"] = relationship(
        "Organization", back_populates="members"
    )

    sessions: Mapped[list["InterviewSession"]] = relationship(
        "InterviewSession", back_populates="user", cascade="all, delete-orphan"
    )

    live_interview_sessions: Mapped[list["LiveInterviewSession"]] = relationship(
        "LiveInterviewSession",
        back_populates="user",
        cascade="all, delete-orphan",
        passive_deletes=True,
    )

    resume_documents: Mapped[list["ResumeDocument"]] = relationship(
        "ResumeDocument",
        back_populates="user",
        cascade="all, delete-orphan",
        passive_deletes=True,
    )

    document_chunks: Mapped[list["DocumentChunk"]] = relationship(
        "DocumentChunk",
        back_populates="user",
        cascade="all, delete-orphan",
        passive_deletes=True,
    )

    refresh_tokens: Mapped[list["RefreshToken"]] = relationship(
        "RefreshToken",
        back_populates="user",
        cascade="all, delete-orphan",
        passive_deletes=True,
    )

    password_reset_tokens: Mapped[list["PasswordResetToken"]] = relationship(
        "PasswordResetToken",
        back_populates="user",
        cascade="all, delete-orphan",
        passive_deletes=True,
    )

    def __repr__(self) -> str:
        return f"<User id={self.id} email={self.email!r}>"
