from __future__ import annotations

import uuid
from datetime import datetime
from typing import TYPE_CHECKING

from sqlalchemy import DateTime, String, Uuid, func
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database import Base

if TYPE_CHECKING:
    from app.models.interview import InterviewSession


class User(Base):
    """
    ORM model for the `users` table.

    Stores credentials and identity for every registered account.
    One row per user — no organisation or role concept in the MVP.
    """

    __tablename__ = "users"

    # ------------------------------------------------------------------
    # Primary key
    #
    # UUID rather than an auto-incrementing integer for two reasons:
    #   1. IDs are exposed in API URLs. Sequential integers reveal the
    #      total number of users and make enumeration trivial — a
    #      meaningful privacy leak for an interview platform.
    #   2. UUIDs can be generated in Python before the INSERT, so the
    #      application knows the ID without a database round-trip.
    #      This simplifies code that constructs related objects in memory.
    #
    # sqlalchemy.Uuid (SQLAlchemy 2.x): cross-database UUID type.
    # Maps to the native UUID column in PostgreSQL and to CHAR(32) in
    # SQLite, which lets the test suite run without Docker.
    # Always returns Python uuid.UUID objects (not raw strings).
    #
    # default=uuid.uuid4: Python-side callable invoked before each INSERT.
    # The id is available immediately after db.add(user), before db.commit().
    # ------------------------------------------------------------------
    id: Mapped[uuid.UUID] = mapped_column(
        Uuid,
        primary_key=True,
        default=uuid.uuid4,
        comment="Unique user identifier. Generated by the application layer.",
    )

    # ------------------------------------------------------------------
    # Email address
    #
    # unique=True: enforced at the database level with a UNIQUE constraint,
    # not just at the application level. This prevents duplicate accounts
    # even under concurrent registration requests that both pass the
    # application-level check before either commits.
    #
    # index=True: creates a B-tree index on this column. Login queries
    # filter by email on every request — without an index, PostgreSQL
    # performs a sequential scan of the entire users table.
    #
    # String(255): matches the VARCHAR(255) in the SQL schema. 255 is the
    # conventional maximum for email addresses per RFC 5321.
    # ------------------------------------------------------------------
    email: Mapped[str] = mapped_column(
        String(255),
        unique=True,
        nullable=False,
        index=True,
        comment="User email address. Used as the login identifier.",
    )

    # ------------------------------------------------------------------
    # Password (hashed)
    #
    # The plaintext password is NEVER stored. The application passes the
    # plaintext through bcrypt (via passlib) which produces a string in
    # the Modular Crypt Format, e.g.:
    #   $2b$12$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36zLrvKSHXaHPHVFxDtM0e.
    #
    # This string encodes the algorithm ($2b$ = bcrypt), the cost factor
    # (12 rounds of key stretching), the salt (22 characters), and the
    # hash (31 characters). Total length is always 60 characters for bcrypt
    # — String(255) gives ample headroom if a different algorithm is used later.
    #
    # Verification: passlib.context.verify(plain_password, hashed_password)
    # The original password cannot be recovered from the stored hash.
    # ------------------------------------------------------------------
    hashed_password: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
        comment="bcrypt hash of the user password. Plaintext is never stored.",
    )

    # ------------------------------------------------------------------
    # Display name
    #
    # Stored as entered by the user at registration. Not used for
    # authentication — only for display in the UI and reports.
    # ------------------------------------------------------------------
    full_name: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
        comment="User's full name as entered at registration.",
    )

    # ------------------------------------------------------------------
    # Timestamp
    #
    # DateTime(timezone=True): maps to TIMESTAMPTZ in PostgreSQL, which
    # stores the moment in UTC regardless of the server's local timezone.
    # Always use timezone-aware timestamps — naive datetimes (without tz)
    # cause subtle bugs when comparing or sorting across timezone boundaries.
    #
    # server_default=func.now(): the default is computed by PostgreSQL
    # (NOW() → current transaction timestamp) rather than Python. This
    # guarantees the value is set even if a row is inserted by a migration
    # script or a direct SQL statement that bypasses the ORM.
    #
    # The Mapped[datetime] annotation (not Mapped[datetime | None]) tells
    # SQLAlchemy 2.x that this column is NOT NULL without needing an
    # explicit nullable=False argument.
    # ------------------------------------------------------------------
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        comment="UTC timestamp of account creation. Set by the database.",
    )

    # Convenience navigation — lets code do `user.sessions` without a query.
    # Cascade all, delete-orphan: deleting a User ORM object also deletes
    # their sessions (DB-level CASCADE handles it for direct SQL deletes).
    sessions: Mapped[list["InterviewSession"]] = relationship(
        "InterviewSession", back_populates="user", cascade="all, delete-orphan"
    )

    def __repr__(self) -> str:
        return f"<User id={self.id} email={self.email!r}>"
